# Generated by Django 2.0.3 on 2018-03-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='classstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassName', models.CharField(max_length=50)),
                ('Building', models.CharField(max_length=50)),
                ('ClassStatus', models.IntegerField()),
                ('UpdateTime', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='week',
        ),
    ]
