# Generated by Django 2.0.3 on 2018-03-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0003_otsteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='classstatus',
            name='CardName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
