# Generated by Django 2.0.3 on 2018-03-25 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0005_otsteam_tel'),
    ]

    operations = [
        migrations.CreateModel(
            name='building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Area', models.CharField(max_length=50)),
            ],
        ),
    ]
