# Generated by Django 2.0.3 on 2018-03-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0006_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='Bid',
            field=models.CharField(default='', max_length=50),
        ),
    ]
