# Generated by Django 2.0.3 on 2018-03-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0007_building_bid'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
    ]
