# Generated by Django 2.0.3 on 2018-03-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0008_eventtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='troubleevent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Person', models.CharField(max_length=50)),
                ('EventClass', models.CharField(max_length=50)),
                ('BeginDtime', models.DateTimeField()),
                ('EndDtime', models.DateTimeField()),
                ('EventType', models.CharField(max_length=50)),
                ('Edescribe', models.CharField(max_length=50)),
                ('Resolvent', models.CharField(max_length=50)),
            ],
        ),
    ]
