# Generated by Django 2.0.3 on 2018-04-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0011_classtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jgh', models.CharField(max_length=50)),
                ('jgxm', models.CharField(max_length=50)),
                ('Dwmc', models.CharField(max_length=200)),
                ('CardID', models.CharField(max_length=50)),
                ('Xn', models.CharField(max_length=50)),
                ('xq', models.CharField(max_length=50)),
                ('Zc', models.CharField(max_length=50)),
                ('Jc', models.CharField(max_length=50)),
                ('Skdd', models.CharField(max_length=200)),
                ('Skap', models.CharField(max_length=200)),
                ('Kcmc', models.CharField(max_length=100)),
                ('Bjmc', models.CharField(max_length=150)),
                ('Skbjrs', models.CharField(max_length=50)),
            ],
        ),
    ]
