# Generated by Django 2.0.3 on 2018-04-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0013_auto_20180401_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_table',
            name='Zc',
            field=models.CharField(default='', max_length=50),
        ),
    ]
